- name: Check that asdf is in location we expect
  tags: asdf
  stat:
    path: ~/.asdf
  register: asdf_folder

- name: Install asdf
  tags: asdf
  git:
    repo: "{{ asdf_git_url }}"
    dest: ~/.asdf
    version: "{{ asdf_branch }}"
  when: not asdf_folder.stat.exists

