- name: Check if asdf is present
  tags: asdf
  command: asdf --version
  register: check_asdf
  ignore_errors: true

- name: Check that asdf is in location and version we expect
  tags: asdf
  block:
    - stat:
        path: ~/.asdf
      register: asdf_folder
    - fail:
        msg: >-
          An old `asdf` binary is present and not at the expected
          location of `/usr/local/bin/just`. Cowardly refusing to proceed.
      when: not asdf_folder.stat.exists
  when: check_asdf.rc == 0 and check_asdf.stdout != asdf_version

- name: Install asdf
  tags: asdf
  git:
    repo: "{{ asdf_git_url }}"
    dest: ~/.asdf
    version: "{{ asdf_branch }}"
  when: check_asdf.rc != 0 or check_asdf.stdout != asdf_version

