- name: Check if asdf is present
  command: asdf --version
  register: check_asdf
  ignore_errors: true

- name: Check that asdf is in location we expect
  block:
    - stat:
        path: ~/.asdf
      register: asdf_folder
    - fail:
        msg: >-
          An old `asdf` version is present and not at the expected
          location of `~/.asdf`. Cowardly refusing to proceed.
      when: not asdf_folder.stat.exists
  # Only worry about file location when we have an old asdf folder
  # We don't care where the asdf binary is if it's current.
  when: check_asdf.rc == 0 and check_asdf.stdout != asdf_version

- name: Install asdf
  ansible.builtin.git:
    repo: "{{ asdf_git_url }}"
    dest: ~/.asdf
    version: "{{ asdf_branch }}"

  when: check_asdf.rc != 0
