inoremap kj <esc>
nnoremap U <c-r>
nnoremap Y y$

" normal mode whitespace
nnoremap <cr> o<esc>
nnoremap <s-cr> O<esc>

" indenting
nnoremap <tab> >>
nnoremap <s-tab> <<
vnoremap <tab> >
vnoremap <s-tab> <
inoremap <tab> <c-t>
inoremap <s-tab> <c-d>

" split line (compliment of <s-j> to join)
nnoremap <s-k> hr<cr>^

" navigation
nnoremap H ^
vnoremap H ^
onoremap H ^
nnoremap L $
vnoremap L $
onoremap L $
nnoremap <c-j> <c-d>
vnoremap <c-j> <c-d>
nnoremap <c-k> <c-u>
vnoremap <c-k> <c-u>

" control-keys for select all, undo, save, cut, copy, paste, quit
nnoremap <c-a> ggVG
nnoremap <c-s> :w<cr>
inoremap <c-s> <esc>:w<cr>a
nnoremap <c-z> u
vnoremap <c-x> "+d
vnoremap <c-c> "+y
nnoremap <c-v> "+p
vnoremap <c-v> "+p
inoremap <c-v> <esc>"+pa
nnoremap <c-w> :q<cr>
inoremap <c-w> <esc>:q<cr>
vnoremap <c-w> <esc>:q<cr>

" leader key
let mapleader=" "
" swap word under cursor with yank register
nnoremap <silent> <leader>s viwp
" swap word under cursor with system clipboard
nnoremap <silent> <leader>S viw"+p
" trim trailing spaces in file
nnoremap <silent> <leader>t :%s/[ \t]\+$//<cr>

" auto-close F# quotations and attributes
inoremap <@ <@ @><Left><Left><Left>
inoremap [< [<lt>>]<Left><Left>


" enable backspace
set backspace=indent,eol,start

" indentation settings
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent

" wrap settings
set textwidth=120
" set colorcolumn=+1 "TODO: add this back once you find out why it gives visual studio an error

" find settings
set ignorecase
set smartcase
set hlsearch
" clear search highlight with Backspace
nnoremap <silent> <bs> :noh<cr><bs>

" max time between key presses to trigger a multi-key binding
set timeoutlen=400

set shell=/bin/bash.exe

