- name: update repo cache
  tags: apt,base
  become: yes
  changed_when: False
  apt:
    update_cache: yes

- name: Install APT requirements
  become: yes
  apt:
    name: [
      'build-essential',
      'unzip',
      'curl',
      'git'
    ]

