#!/bin/bash

# Default values
directory='*'
by="s/ / /"
verbose=false
preview=false

# allows for the use of ** for recursive globbing
shopt -s globstar
# Use case-insensitive filename globbing
shopt -s nocaseglob
# includes hidden items by default
shopt -s dotglob

[[ $# == 0 ]] && {
  echo "rename_selected called with no arguments!"
  echo "rename_selected must be called with at least 1 argument"
  echo "use 'rename_selected -h' to see possible arguments"
  exit 1
}

while [[ $# > 0 ]]
do
  case "$1" in

    -d|--directory)
      directory="$2"
      shift
      ;;

    -b|--by)
      by="$2"
      shift
      ;;

    -v|--verbose)
      verbose=true
      ;;

    -p|--preview)
      verbose=true
      preview=true
      ;;

    -h|--help)
      echo "Command rename_selected:"
      echo "Utility for renaming folders and files"
      echo "Short flag stacking is NOT supported!"
      echo "
      Sets the follow shopt at script level:
      shopt -s globstar
      shopt -s nocaseglob
      shopt -s dotglob
      "
      echo "Usage:"

      echo "    -d|--directory
      Optional
      Type: String of directory glob
      Default is: '$directory'
      The directory glob to rename folders and files in.
      "

      echo "    -b|--by
      Optional but recommended. Nothing will happen without this.:w
      Type: String executed by sed -E
      Default is: $by
      Program executed by 'sed -E' on each file name to derive new file name.
      You can do multiple s/// by doing: --by 's///;s///;s///;'
      "

      echo "    -v|--verbose
      Optional
      Type: Takes no argument
      Display the renames happening.
      "

      echo "    -p|--preview
      Optional
      Type: Takes no argument
      When specified, it does not preform the renames.
      When specified, it also toggles -v on.
      For debugging and 'previewing' the change before performing it.
      "

      echo "    -h|--help"
      exit 1
      ;;
  
    *)
      echo "command called with non valid flags!"
      echo "use 'rename_selected -h' to see options"
      exit 1
      ;;

  esac
  shift
done

[[ $verbose == true ]] && {
  echo "directory: $directory"
  echo "by: $by"
  echo "verbose: $verbose"
  echo "preview: $preview"
}

IFS= ;
for f in $directory
do
  new_name=$(echo $f | sed -E "$by")
  [[ $f == $new_name ]] && {
    [[ $verbose == true ]] && {
      echo "No name change for file/folder $f";
      }
    }
  [[ $f != $new_name ]] && {
    [[ $verbose == true ]] && {
      echo "mv \"$f\" \"$new_name\"";
      }
    [[ $preview == false ]] && {
      mv "$f" "$new_name";
      }
    }
done
unset IFS;

