- name: Download and Install microsoft_packages
  tags: microsoft_packages
  shell: |
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm /tmp/packages-microsoft-prod.deb

