- name: Check if just is present and correct version
  tags: just
  command: just --version
  register: check_just
  ignore_errors: true

- name: Check that just is in location we expect
  tags: just
  block:
    - stat:
        path: /usr/local/bin/just
      register: just_file
    - fail:
        msg: >-
          An old `just` binary is present and not at the expected
          location of `/usr/local/bin/just`. Cowardly refusing to proceed.
      when: not just_file.stat.exists
  # Only worry about file location when we have an old just binary
  # We don't care where the just binary is if it's current.
  when: check_just.rc == 0 and check_just.stdout != just_version

- name: Install just
  tags: just
  block:

    - name: Install just | Execute the install script
      shell: |
        dest="/usr/local/bin"
        td=$(mktemp -d || mktemp -d -t tmp)
        curl -0Lks "{{just_url}}" | tar -C $td -xz

        for f in $(ls $td); do
          test -x $td/$f || continue

          if [ -e "$dest/$f" ] && [ $force = false ]; then
            err "$f already exists in $dest"
          else
            mkdir -p $dest
            install -m 755 $td/$f $dest
          fi
        done
        rm -rf $td

      become: yes

  when: check_just.rc != 0
