- name: update repo cache
  become: yes
  tags: apt,dev
  change_when: False
  apt:
    update_cache: yes

- name: Install APT requirements
  become: yes
  tags: apt,dev
  apt:
    name: [
      'build-essential',
      'unzip',
      'ripgrep',
      'fzf',
      'tmux',
      'dos2unix',
      'tree',
      'checkinstall',
      'libssl-dev',
      'apt-transport-https',
      'dotnet-sdk-5.0'
    ]

- include_role:
    name: asdf

- include_role:
    name: nvm

