- name: Check that nvm is in location we expect
  tags: nvm
  stat:
    path: ~/.nvm
  register: nvm_folder

- name: Install nvm
  tags: nvm
  shell: |
    curl -o- HTTPS://raw.githubusercontent.com/creationix/nvm/v0.35.1/install.sh | bash
  when: not asdf_folder.stat.exists

