nmap <leader>cs :cs find s <cword><cr>
nmap <leader>cs :cs find g <cword><cr>
nmap <leader>cs :cs find c <cword><cr>
nmap <leader>cs :cs find t <cword><cr>
nmap <leader>cs :cs find e <cword><cr>
nmap <leader>cs :cs find f <cword><cr>
nmap <leader>cs :cs find i <cword><cr>
nmap <leader>cs :cs find d <cword><cr>
nmap <leader>cs :cs find a <cword><cr>
nmap <leader>cs :cs find b <cword><cr>
